repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.25.0
  hooks:
  - id: yapf
    language: system
- repo: local
  hooks:
  - id: prospector
    name: prospector
    entry: prospector
    types: [file, python]
    language: system
    exclude: '^(doc/)|(examples/)|(futures/)'
