repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.22.0
  hooks:
  - id: yapf
    language: system
- repo: git://github.com/guykisel/prospector-mirror
  sha: b27f281eb9398fc8504415d7fbdabf119ea8c5e1
  hooks:
  - id: prospector
    language: system
    exclude: '^(doc/)'
